spring:
  application:
    name: first-application-spring-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/first_spring_boot_diih?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jpa:
    hibernate:
       ddl-update: update
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false